name: Setup VM Credentials
description: |
  This action will setup the runner with the necessary credentials to create and
  interact with VMs

inputs:
  gcp-ssh-key:
    description:
      The SSH private key to use for GCP
  gcp-ssh-key-pub:
    description:
      The SSH public key to use for GCP
  s390x-key:
    description:
      The SSH private key to use for s390x
  ppc64le-key:
    description:
      The SSH private key to use for ppc64le
runs:
  using: composite
  steps:
    - shell: bash
      run: |
          mkdir -p /tmp/secret/stackrox-collector-e2e-tests
          cp "$GOOGLE_APPLICATION_CREDENTIALS" /tmp/secret/stackrox-collector-e2e-tests/GOOGLE_CREDENTIALS_COLLECTOR_SVC_ACCT

          mkdir -p "$HOME/.ssh"
          chmod 0700 "$HOME/.ssh"

          function copy_secret_to_file() {
            local secret="$1"
            local destination="$2"
            local perms="$3"

            echo "$secret" > "$destination"
            chmod "$perms" "$destination"
          }

          copy_secret_to_file "${{ inputs.gcp-ssh-key }}" "$HOME/.ssh/google_compute_engine" 0600
          copy_secret_to_file "${{ inputs.gcp-ssh-key-pub }}" "$HOME/.ssh/google_compute_engine.pub" 0600
          copy_secret_to_file "${{ inputs.s390x-key }}" "$HOME/.ssh/acs-s390x-rsa.prv" 0600
          copy_secret_to_file "${{ inputs.ppc64le-key }}" "$HOME/.ssh/acs-ppc64le-rsa.prv" 0600

          ls -lah $HOME/.ssh/

    - shell: bash
      run: |
        ansible-galaxy collection install -r "${{ github.workspace }}/ansible/requirements.yml"

    # Added workaround for ssh connection issue with power vm from ubuntu machine.
    # Changing mtu works in resolving the issue
    - shell: bash
      run: sudo ifconfig eth0 mtu 1000 up

