---

- name: Destroy X86 VM
  delegate_to: localhost
  google.cloud.gcp_compute_instance:
    name: "{{ inventory_hostname }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    # zone is set by the GCP inventory automatically
    zone: "{{ zone }}"
    state: absent
  when: arch_info == "x86"

- name: Delete IBM Z VM
  include_tasks: destroy-s390x-vm.yml
  when: arch_info == "s390x"

- name: Delete IBM Power VSI
  include_tasks:
    apply:
      delegate_to: localhost
    file: destroy-ppc64le-vm.yml
  when: arch_info == "ppc64le"
