---

- name: Check platform excluded
  set_fact:
    excluded: "{{ test_platform in excluded_vms }}"

- name: Check family excluded
  set_fact:
    excluded: "{{ vm_family in excluded_vms }}"
  when: vm_image is not defined and excluded == false

- name: Check image excluded
  set_fact:
    excluded: "{{ vm_image in excluded_vms }}"
  when: vm_image is defined and excluded == false

- block:
  - name: Create IBM Z VM
    include_tasks: create-s390x-vm.yml
    vars:
      vsi_name: "{{ vm_name }}"
      vsi_zone: "{{ zone.name }}"
      vsi_subnet_id: "{{ zone.subnet_id }}"
      condition: "{{ (instance_result | default({'changed': false })).changed }}"
    when: vm_arch == "s390x" and not condition
    loop: "{{ s390x.zones }}"
    loop_control:
      loop_var: zone
    register: instance_result

  - name: Create IBM POWER VM
    include_tasks: create-ppc64le-vm.yml
    vars:
      pi_name: "{{ vm_name }}"
    when: vm_arch == "ppc64le"

  - name: Create GCP VM
    include_tasks: create-gcp-vm.yml
    when: (vm_arch == "amd64" or vm_arch == "arm64")

  when: excluded == false

# make sure to reset the instance_result otherwise subsequent VMs arent created
- set_fact:
    instance_result:
      changed: false
