---

- block:
    - name: Start docker service
      service:
        name: "docker"
        enabled: true
        state: started
  rescue:
    - name: Use shell to try to force start
      shell: systemctl enable docker && systemctl start docker

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Reset SSH connection for group propagation
  meta: reset_connection
