---
- name: Get distro info
  shell: awk -F= '$1=="ID" { print $2 ;}' /etc/os-release
  register: distro

- name: Register server with Red Hat for IBM POWER vms
  tags: attach_subscription
  community.general.redhat_subscription:
    state: present
    username: "{{ redhat_username }}"
    password: "{{ redhat_password }}"
    auto_attach: true
  register: registration
  retries: 2
  until: registration is not failed
  when: arch_info == "ppc64le"


#added repository from centos as power is not supporting rhel distro. see more https://docs.docker.com/engine/install/rhel/ 

- name: Add repository
  shell: |
    yum install -y yum-utils device-mapper-persistent-data lvm2
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum-config-manager --setopt="docker-ce-stable.baseurl=https://download.docker.com/linux/centos/\$releasever/\$basearch/stable" --save 
 
- name: Install docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: true

