---
- set_fact:
    distro: centos

- when: arch_info == "s390x"
  block:
    - name: Get distro info
      shell: awk -F= '$1=="ID" { print $2 ;}' /etc/os-release
      register: distro_id
      when: arch_info == "s390x"

    - set_fact:
        distro: "{{ distro_id.stdout }}"

- name: Register server with Red Hat for IBM POWER vms
  tags: attach_subscription
  community.general.redhat_subscription:
    state: present
    username: "ashwini.kadam"
    password: "***REMOVED***"
    auto_attach: true
  register: registration
  retries: 2
  delay: 30
  until: registration is not failed
  when: arch_info == "ppc64le" or arch_info == "s390x"

- name: Add repository
  shell: |
    yum install -y yum-utils device-mapper-persistent-data lvm2
    yum-config-manager --add-repo https://download.docker.com/linux/"{{ distro }}"/docker-ce.repo
    yum-config-manager --setopt="docker-ce-stable.baseurl=https://download.docker.com/linux/"{{ distro }}"/\$releasever/\$basearch/stable" --save
    yum update -y

- name: Install docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: true

