---
- set_fact:
    distro: centos


- name: Register server with Red Hat for IBM Z vms
  tags: attach_subscription
  community.general.redhat_subscription:
    state: present
    username: "{{ redhat_username }}"
    password: "{{ redhat_password }}"
    auto_attach: true
  register: registration
  retries: 2
  delay: 30
  until: registration is not failed
  when: arch_info == "ppc64le"

- name: DEBUG list repos
  shell: |
    subscription-manager repos --list
    subscription-manager repos --list-enabled
  register: subscription
  when: arch_info == "ppc64le"

- debug:
    var: subscription

- name: Add repository
  shell: |
    yum-config-manager --add-repo https://download.docker.com/linux/"{{ distro }}"/docker-ce.repo
    yum-config-manager --setopt="docker-ce-stable.baseurl=https://download.docker.com/linux/"{{ distro }}"/\$releasever/\$basearch/stable" --save
    yum update -y 

- name: Install docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: true

