apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-close-ports-load
  #namespace: ports-load-test
  labels:
    app: open-close-ports-load
spec:
  replicas: 6
  selector:
    matchLabels:
      app: open-close-ports-load
  template:
    metadata:
      labels:
        app: open-close-ports-load
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: open-close-ports-load
        image: quay.io/rhacs-eng/qa:collector-open-close-ports-load-3.12.x-105-g86df7514aa-dirty
