---
- name: Create Build VMs
  hosts: localhost
  tags:
    - setup
  tasks:
    - name: Create VMs for each architecture
      include_role:
        name: create-all-vms
      vars:
        vm_list:
          s390x: "{{ virtual_machines['rhel-s390x'] | combine({'families': ['rhel-8-6-s390x'] }) }}"
          ppc64le: "{{ virtual_machines['rhel-ppc64le'] | combine({'families': ['p']}) }}"
          arm64: "{{ virtual_machines['rhel-arm64'] | combine({'families': ['rhel-9-arm64']}) }}"

- name: Provision Build VMs
  hosts: "job_id_{{ job_id }}"
  roles:
    - provision-vm
  gather_facts: no
  strategy: free
  become: yes
  tags:
    - setup
    - provision
