---

- name: Build test binary
  make:
    chdir: "{{ collector_root }}/integration-tests"
    target: build
    params:
      GOARCH: "{{ arch | default('amd64') }}"
      GOOS: linux
  delegate_to: localhost

- name: Make directory structure
  shell: |
    mkdir -p /tmp/collector-testing/container

- name: Upload test binary
  copy:
    src: "{{ collector_root }}/integration-tests/bin/collector-tests"
    dest: /tmp/collector-testing/
    mode: '0700'

- name: Upload test files
  copy:
    src: "{{ collector_root }}/integration-tests/images.yml"
    dest: "/tmp/collector-testing/images.yml"
    mode: '0600'

