name: Collector image build

on:
  workflow_call:
    inputs:
      collector-tag:
        type: string
        required: true
        description: |
          The tag used to build the collector image
      collector-image:
        type: string
        required: true
        description: |
          Basic stackrox-io image built
      collector-builder-tag:
        type: string
        required: true
        description: |
          The builder tag to use in the build

env:
  COLLECTOR_TAG: ${{ inputs.collector-tag }}
  COLLECTOR_BUILDER_TAG: ${{ inputs.collector-builder-tag }}
  RHACS_ENG_IMAGE: quay.io/rhacs-eng/collector:${{ inputs.collector-tag }}

jobs:
  build-collector-image:
    name: Build the collector slim image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, ppc64le, s390x]

    env:
      PLATFORM: linux/${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install python dependencies
        run: python -m pip install -r ansible/requirements.txt

      - name: Install ansible dependencies
        run: ansible-galaxy collection install -r ansible/ansible-collections.yml

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_COLLECTOR_SVC_ACCT }}'

      - name: Setup GCP
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Set environment
        if: matrix.arch != 'amd64'
        run: |
          if [[ "${{ matrix.arch }}" == 's390x' ]]; then
            {
              echo "IBM_CLOUD_SSH_LEY<<EOS"
              echo "${{ secrets.IBM_CLOUD_S390X_SSH_PRIVATE_KEY }}"
              echo "EOS"

              echo "IBM_CLOUD_SSH_PUB_KEY="
              echo "IBM_API_KEY=${{ secrets.IBM_CLOUD_S390X_API_KEY }}"
              echo "VM_TYPE=rhel-s390x"
            } >> "${GITHUB_ENV}"
          fi

          if [[ "${{ matrix.arch }}" == 'ppc64le' ]]; then
            {
              echo "IBM_CLOUD_SSH_KEY<<EOS"
              echo "${{ secrets.IBM_CLOUD_POWER_SSH_PRIVATE_KEY }}"
              echo "EOS"

              echo "IBM_CLOUD_SSH_PUB_KEY=${{ secrets.IBM_CLOUD_POWER_SSH_PUBLIC_KEY }}"
              echo "IBM_API_KEY=${{ secrets.IBM_CLOUD_POWER_API_KEY }}"
              echo "VM_TYPE=rhel-ppc64le"
            } >> "${GITHUB_ENV}"
          fi

      - name: Setup Ansible
        uses: ./.github/actions/setup-ansible-env
        if: matrix.arch != 'amd64'
        with:
          vm-type: ${{ env.VM_TYPE }}
          job-tag: ""
          gcp-ssh-key: ${{ secrets.GCP_SSH_KEY }}
          gcp-ssh-pub-key: ${{ secrets.GCP_SSH_KEY_PUB }}
          redhat-username: ${{ secrets.REDHAT_USERNAME }}
          redhat-password: ${{ secrets.REDHAT_PASSWORD }}
          ibm-ssh-key: ${{ env.IBM_CLOUD_SSH_KEY }}
          ibm-ssh-pub-key: ${{ env.IBM_CLOUD_SSH_PUB_KEY }}
          ibm-api-key: ${{ env.IBM_API_KEY }}

      - name: Create VM
        if: matrix.arch != 'amd64'
        run: |
          make -C "${{ github.workspace }}/ansible" create-vms

      - name: Checks PR, main and release branches
        run: |
          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            echo "COLLECTOR_APPEND_CID=true" >> "$GITHUB_ENV"

            if [[ "${{ contains(github.event.pull_request.labels.*.name, 'address-sanitizer') }}" == "true" ]]; then
              echo "ADDRESS_SANITIZER=true" >> "$GITHUB_ENV"
            fi
          fi

      - name: Create secrets.yml
        run: |
          {
            echo "---"
            echo "stackrox_io_username: ${{ secrets.QUAY_STACKROX_IO_RW_USERNAME }}"
            echo "stackrox_io_password: ${{ secrets.QUAY_STACKROX_IO_RW_PASSWORD }}"
            echo "rhacs_eng_username: ${{ secrets.QUAY_RHACS_ENG_RW_USERNAME }}"
            echo "rhacs_eng_password: ${{ secrets.QUAY_RHACS_ENG_RW_PASSWORD }}"
          } > ${{ github.workspace }}/ansible/secrets.yml

      - name: Build images
        if: |
          github.event_name == 'push' || matrix.arch == 'amd64'
        timeout-minutes: 480
        run: |
          ansible-galaxy install -r ansible/requirements.yml
          ansible-playbook \
            --connection local \
            -i localhost, \
            --limit localhost \
            -e collector_image='${{ inputs.collector-image }}' \
            -e arch='${{ matrix.arch }}' \
            -e @'${{ github.workspace }}/ansible/secrets.yml' \
            ansible/ci-build-collector.yml
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg

      - name: Build images
        if: |
          github.event_name == 'push' ||
          (matrix.arch != 'amd64' &&
          !contains(github.event.pull_request.labels.*.name, 'skip-multiarch-builds'))
        working-directory: ansible
        run: |
          ansible-galaxy install -r ansible/requirements.yml
          ansible-playbook \
            -i ci \
            -e collector_image='${{ inputs.collector-image }}' \
            -e arch='${{ matrix.arch }}' \
            -e @secrets.yml \
            ci-build-collector.yml

      - name: Destroy VMs
        if: always() && matrix.arch != 'amd64'
        run: |
          make -C "${{ github.workspace }}/ansible" destroy-vms

  create-multiarch-manifest:
    needs:
    - build-collector-image
    name: Create Multiarch manifest
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      !contains(github.event.pull_request.labels.*.name, 'skip-multiarch-builds')
    env:
      ARCHS: amd64 ppc64le s390x

    steps:
      - uses: actions/checkout@v3

      - name: Login to quay.io/stackrox-io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_STACKROX_IO_RW_USERNAME }}
          password: ${{ secrets.QUAY_STACKROX_IO_RW_PASSWORD }}

      - name: Create and push multiarch manifest for stackrox-io -slim
        uses: ./.github/actions/create-multiarch-manifest
        with:
          base-image: quay.io/stackrox-io/collector:${{ inputs.collector-tag }}
          archs: ${{ env.ARCHS }}
          suffix: -slim

      - name: Create and push multiarch manifest for stackrox-io -base
        uses: ./.github/actions/create-multiarch-manifest
        with:
          base-image: quay.io/stackrox-io/collector:${{ inputs.collector-tag }}
          archs: ${{ env.ARCHS }}
          suffix: -base

      - name: Login to quay.io/rhacs-eng
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_RHACS_ENG_RW_USERNAME }}
          password: ${{ secrets.QUAY_RHACS_ENG_RW_PASSWORD }}

      - name: Create and push multiarch manifest for rhacs-eng -slim
        uses: ./.github/actions/create-multiarch-manifest
        with:
          base-image: quay.io/rhacs-eng/collector:${{ inputs.collector-tag }}
          archs: ${{ env.ARCHS }}
          suffix: -slim

      - name: Create and push multiarch manifest for rhacs-eng -base
        uses: ./.github/actions/create-multiarch-manifest
        with:
          base-image: quay.io/rhacs-eng/collector:${{ inputs.collector-tag }}
          archs: ${{ env.ARCHS }}
          suffix: -base

  retag-x86-image:
    needs:
    - build-collector-image
    name: Retag x86 slim image
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'skip-multiarch-builds')
    steps:
      - name: Pull image to retag
        run: |
          docker pull ${{ inputs.collector-image }}-amd64-slim

      - name: Retag and push stackrox-io -slim
        uses: stackrox/actions/images/retag-and-push@v1
        with:
          src-image: ${{ inputs.collector-image }}-amd64-slim
          dst-image: ${{ inputs.collector-image }}-slim
          username: ${{ secrets.QUAY_STACKROX_IO_RW_USERNAME }}
          password: ${{ secrets.QUAY_STACKROX_IO_RW_PASSWORD }}

      - name: Retag and push stackrox-io -base
        uses: stackrox/actions/images/retag-and-push@v1
        with:
          src-image: ${{ inputs.collector-image }}-amd64-slim
          dst-image: ${{ inputs.collector-image }}-base
          username: ${{ secrets.QUAY_STACKROX_IO_RW_USERNAME }}
          password: ${{ secrets.QUAY_STACKROX_IO_RW_PASSWORD }}

      - name: Retag and push rhacs-eng -slim
        uses: stackrox/actions/images/retag-and-push@v1
        with:
          src-image: ${{ inputs.collector-image }}-amd64-slim
          dst-image: ${{ env.RHACS_ENG_IMAGE }}-slim
          username: ${{ secrets.QUAY_RHACS_ENG_RW_USERNAME }}
          password: ${{ secrets.QUAY_RHACS_ENG_RW_PASSWORD }}

      - name: Retag and push rhacs-eng -base
        uses: stackrox/actions/images/retag-and-push@v1
        with:
          src-image: ${{ inputs.collector-image }}-amd64-slim
          dst-image: ${{ env.RHACS_ENG_IMAGE }}-base
          username: ${{ secrets.QUAY_RHACS_ENG_RW_USERNAME }}
          password: ${{ secrets.QUAY_RHACS_ENG_RW_PASSWORD }}
