name: Collector Integration Tests

on:
  workflow_call:
    inputs:
      vm_type:
        description: |
          Type of VM to run integration tests on. e.g. rhel or ubuntu-os
        type: string
        required: true
      collector-tag:
        description: |
          Tag used for running the integration tests
        type: string
        required: true
      offline-mode:
        description: |
          Set to true to enable collector running in offline mode
        type: boolean
        default: false
      run-benchmarks:
        description: |
          Whether to run the benchmarks instead of the integration tests
        type: boolean
        default: false
      job-tag:
        description: |
          Used to differentiate between different sources when creating
          VMs in GCP.
        type: string
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      COLLECTOR_IMAGE: quay.io/rhacs-eng/collector:${{ inputs.collector-tag }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19' # to match the requirement in the integration tests
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install python dependencies
        run: python -m pip install -r ansible/requirements.txt

      - name: Install ansible dependencies
        run: ansible-galaxy collection install -r ansible/ansible-collections.yml

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_COLLECTOR_SVC_ACCT }}'

      - name: Setup GCP
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Set environment
        run: |
          if [[ '${{ contains(github.event.pull_request.labels.*.name, 'integration-tests-trace-logging') }}' == 'true' ]]; then
            echo "COLLECTOR_LOG_LEVEL=trace" | tee -a "$GITHUB_ENV"
          fi

          if [[ "${{ inputs.vm_type }}" =~ s390x ]]; then
            {
              echo "IBM_CLOUD_SSH_KEY=${{ secrets.IBM_CLOUD_S390X_PRIVATE_KEY }}"
              echo "IBM_CLOUD_SSH_PUB_KEY="
              echo "IBM_API_KEY=${{ secrets.IBM_CLOUD_S390X_API_KEY }}"
            } >> "${GITHUB_ENV}"
          fi

          if [[ "${{ inputs.vm_type }}" =~ ppc64le ]]; then
            {
              echo "IBM_CLOUD_SSH_KEY=${{ secrets.IBM_CLOUD_POWER_PRIVATE_KEY }}"
              echo "IBM_CLOUD_SSH_PUB_KEY=${{ secrets.IBM_CLOUD_POWER_PUBLIC_KEY }}"
              echo "IBM_API_KEY=${{ secrets.IBM_CLOUD_POWER_API_KEY }}"
            } >> "${GITHUB_ENV}"
          fi

      - name: Create VMs
        id: create-vms
        uses: ./.github/actions/create-vm
        with:
          vm-type: ${{ inputs.vm_type }}
          job-tag: ${{ inputs.job-tag }}
          gcp-service-acct: ${{ secrets.GOOGLE_CREDENTIALS_COLLECTOR_SVC_ACCT }}
          gcp-ssh-key: ${{ secrets.GCP_SSH_KEY }}
          gcp-ssh-pub-key: ${{ secrets.GCP_SSH_KEY_PUB }}
          ibm-ssh-key: ${{ env.IBM_CLOUD_SSH_KEY }}
          ibm-ssh-pub-key: ${{ env.IBM_CLOUD_SSH_PUB_KEY }}
          ibm-api-key: ${{ env.IBM_API_KEY }}
          redhat-username: ${{ secrets.REDHAT_USERNAME }}
          redhat-password: ${{ secrets.REDHAT_PASSWORD }}
          create-benchmark-vms: ${{ inputs.run-benchmarks }}

      - name: Run Tests
        if: ${{ ! inputs.run-benchmarks }}
        run: |
          if [[ "${{ inputs.offline-mode }}" == "true" ]]; then
            export COLLECTOR_OFFLINE_MODE="true"
          fi

          make -C "${{ github.workspace }}/ansible" integration-tests
        env:
          QUAY_RHACS_ENG_RO_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
          QUAY_RHACS_ENG_RO_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
          JOB_ID: ${{ steps.create-vms.outputs.job-id }}
          BUILD_TYPE: ci

      - name: Run Benchmarks
        if: inputs.run-benchmarks
        run: make -C "${{ github.workspace }}/ansible" benchmarks
        env:
          QUAY_RHACS_ENG_RO_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
          QUAY_RHACS_ENG_RO_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
          JOB_ID: ${{ steps.create-vms.outputs.job-id }}
          BUILD_TYPE: ci

      - name: Teardown VMs
        if: always()
        uses: ./.github/actions/destroy-vms
        with:
          job-id: ${{ steps.create-vms.outputs.job-id }}

      - name: Store artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.vm_type }}-logs
          path: |
            ${{ github.workspace }}/integration-tests/container-logs/**/*
            ${{ github.workspace }}/integration-tests/perf.json
            ${{ github.workspace }}/integration-tests/performance-logs/**/*
