name: Collector Integration Tests

on:
  workflow_call:
    inputs:
      collector-tag:
        description: |
          Tag used for running the integration tests
        type: string
        required: true
      collector-qa-tag:
        description: |
          Tag used for QA containers
        type: string
        required: true
      job-tag:
        description: |
          Used to differentiate between different sources when creating
          VMs in GCP.
        type: string
        default: ""

jobs:
  identify-image-platforms:
    runs-on: ubuntu-latest
    outputs:
      supported_archs: "${{ steps.identify-archs.outputs.supported_archs }}"
    steps:
      - id: identify-archs
        run: |
          if docker manifest inspect "${COLLECTOR_IMAGE}"; then
            supported_archs="$(docker manifest inspect "${COLLECTOR_IMAGE}" | jq -c '[.manifests[].platform.architecture]')"
          else
            docker pull "${COLLECTOR_IMAGE}"
            supported_archs="$(docker inspect "${COLLECTOR_IMAGE}" | jq -c '[.[].Architecture]')"
          fi

          echo "supported_archs=${supported_archs}" >> "$GITHUB_OUTPUT"
        env:
          COLLECTOR_IMAGE: "quay.io/stackrox-io/collector:${{ inputs.collector-tag }}"

  amd64-required-integration-tests:
    uses: ./.github/workflows/integration-tests-vm-type.yml
    needs:
      - identify-image-platforms
    if: contains(needs.identify-image-platforms.outputs.supported_archs, 'amd64')
    strategy:
      # ensure that if one part of the matrix fails, the
      # rest will continue
      fail-fast: false
      matrix:
        vm_type:
          - rhel
          - ubuntu-os
    with:
      vm_type: ${{ matrix.vm_type }}
      collector-tag: ${{ inputs.collector-tag }}
      collector-qa-tag: ${{ inputs.collector-qa-tag }}
      job-tag: ${{ inputs.job-tag }}
    secrets: inherit

  amd64-all-integration-tests:
    uses: ./.github/workflows/integration-tests-vm-type.yml
    needs:
      - identify-image-platforms
    if: contains(needs.identify-image-platforms.outputs.supported_archs, 'amd64') &&
        contains(github.event.pull_request.labels.*.name, 'all-integration-tests') ||
        github.event_name == 'push'
    strategy:
      # ensure that if one part of the matrix fails, the
      # rest will continue
      fail-fast: false
      matrix:
        vm_type:
          - cos
          - flatcar
          - fedora-coreos
          - rhel-sap
          - sles
          - garden-linux
          - rhcos
    with:
      vm_type: ${{ matrix.vm_type }}
      collector-tag: ${{ inputs.collector-tag }}
      collector-qa-tag: ${{ inputs.collector-qa-tag }}
      job-tag: ${{ inputs.job-tag }}
    secrets: inherit

  arm64-integration-tests:
    uses: ./.github/workflows/integration-tests-vm-type.yml
    needs:
      - identify-image-platforms
    if: contains(needs.identify-image-platforms.outputs.supported_archs, 'arm64')
    strategy:
      # ensure that if one part of the matrix fails, the
      # rest will continue
      fail-fast: false
      matrix:
        vm_type:
          - rhel-arm64
          - ubuntu-os-arm64
          - sles-arm64
          - fcarm

    with:
      vm_type: ${{ matrix.vm_type }}
      collector-tag: ${{ inputs.collector-tag }}
      collector-qa-tag: ${{ inputs.collector-qa-tag }}
      job-tag: ${{ inputs.job-tag }}
    secrets: inherit

  s390x-integration-tests:
    uses: ./.github/workflows/integration-tests-vm-type.yml
    if: contains(github.event.pull_request.labels.*.name, 'run-multiarch-builds') || github.event_name == 'push'
    with:
      vm_type: rhel-s390x
      collector-tag: ${{ inputs.collector-tag }}
      collector-qa-tag: ${{ inputs.collector-qa-tag }}
      job-tag: ${{ inputs.job-tag }}
    secrets: inherit

  ppc64le-integration-tests:
    uses: ./.github/workflows/integration-tests-vm-type.yml
    if: contains(github.event.pull_request.labels.*.name, 'run-multiarch-builds') || github.event_name == 'push'
    with:
      vm_type: rhel-ppc64le
      collector-tag: ${{ inputs.collector-tag }}
      collector-qa-tag: ${{ inputs.collector-qa-tag }}
      job-tag: ${{ inputs.job-tag }}
    secrets: inherit

  notify:
    runs-on: ubuntu-latest
    if: always() && contains(join(needs.*.result, ','), 'failure') && github.event_name == 'push'
    needs:
      - amd64-required-integration-tests
      - amd64-all-integration-tests
      - arm64-integration-tests
      - s390x-integration-tests
      - ppc64le-integration-tests
    steps:
      - name: Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_COLLECTOR_ONCALL_WEBHOOK }}
          SLACK_CHANNEL: team-acs-collector-oncall
          SLACK_COLOR: failure
          SLACK_LINK_NAMES: true
          SLACK_TITLE: "Integration tests failed."
          MSG_MINIMAL: actions url,commit
          SLACK_MESSAGE: |
            @acs-collector-oncall
