name: Main collector CI

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - 3.*.*
  pull_request:

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  init:
    uses: ./.github/workflows/init.yml

  build-drivers:
    uses: ./.github/workflows/drivers.yml
    with:
      drivers-bucket: ${{ needs.init.outputs.drivers-bucket }}
      bundles-bucket: ${{ needs.init.outputs.bundles-bucket }}
      branch-name: ${{ needs.init.outputs.branch-name }}
    needs: init
    secrets: inherit

  upload-drivers:
    uses: ./.github/workflows/upload-drivers.yml
    with:
      gcp-bucket: ${{ needs.init.outputs.push-drivers-bucket }}
    if: ${{ needs.build-drivers.outputs.parallel-jobs > 0 }}
    needs:
    - init
    - build-drivers
    secrets: inherit

  check-drivers-build:
    uses: ./.github/workflows/check-drivers-failures.yml
    needs: build-drivers
    if: ${{ needs.build-drivers.outputs.parallel-jobs > 0 }}
    secrets: inherit
    with:
      logs-artifact: driver-build-failures

  build-collector-slim-amd64:
    uses: ./.github/workflows/collector-slim.yml
    needs: init
    with:
      collector-tag: ${{ needs.init.outputs.collector-tag }}
      collector-image: ${{ needs.init.outputs.collector-image }}
      arch: amd64
    secrets: inherit

  build-collector-slim-ppc64le:
    uses: ./.github/workflows/collector-slim.yml
    needs:
      - init
      - build-collector-slim-amd64
    with:
      collector-tag: ${{ needs.init.outputs.collector-tag }}
      collector-image: ${{ needs.init.outputs.collector-image }}
      arch: ppc64le
    secrets: inherit

  build-collector-full:
    uses: ./.github/workflows/collector-full.yml
    with:
      collector-tag: ${{ needs.init.outputs.collector-tag }}
      drivers-bucket: ${{ needs.init.outputs.drivers-bucket }}
      skip-built-drivers: ${{ needs.build-drivers.outputs.parallel-jobs == 0 }}
      build-full-image: ${{ github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'build-full-images') }}
    secrets: inherit
    needs:
    - init
    - build-collector-slim-amd64
    - build-drivers

  integration-tests:
    uses: ./.github/workflows/integration-tests.yml
    with:
      collector-tag: ${{ needs.init.outputs.collector-tag }}
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-integration-tests') }}
    needs:
    - init
    - build-collector-slim-amd64
    - build-collector-full
    secrets: inherit

  benchmarks:
    uses: ./.github/workflows/benchmarks.yml
    with:
      collector-tag: ${{ needs.init.outputs.collector-tag }}
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-integration-tests') }}
    needs:
    - init
    - build-collector-slim-amd64
    - build-collector-full
    secrets: inherit

  multiarch-manifest:
    uses: ./.github/workflows/multiarch-manifest.yml
    with:
      collector-tag: ${{ needs.init.outputs.collector-tag }}
    needs:
      - init
      - build-collector-slim-amd64
      - build-collector-slim-ppc64le
    secrets: inherit

  build-support-packages:
    uses: ./.github/workflows/support-packages.yml
    with:
      branch-name: ${{ needs.init.outputs.branch-name }}
      drivers-bucket: ${{ needs.init.outputs.drivers-bucket }}
      support-packages-bucket: ${{ needs.init.outputs.support-packages-bucket }}
      support-packages-index-bucket: ${{ needs.init.outputs.support-packages-index-bucket }}
      public-support-packages-bucket: ${{ needs.init.outputs.public-support-packages-bucket }}
    if: always() && (github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'test-support-packages'))
    needs:
    - init
    - build-drivers
    - upload-drivers
    secrets: inherit

  run-cpaas-steps:
    uses: ./.github/workflows/cpaas.yml
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run-cpaas-steps')
    secrets: inherit
