name: Create Multi-arch Manifest

on:
  workflow_call:
    inputs:
      collector-tag:
        type: string
        required: true
        description: |
          The tag used to build the collector image

jobs:
  set-environment:
    name: Set environment variables
    runs-on: ubuntu-latest
    outputs:
      build-builder-image: ${{ steps.set-env.outputs.build-builder-image }}
      collector-builder-tag: ${{ steps.set-env.outputs.collector-builder-tag }}

    steps:
      - name: Checks PR, main and release branches
        id: set-env
        run: |

          if [[ "${{ github.event_name }}" != 'pull_request' ]]; then
            echo 'build-builder-image=true' >> "$GITHUB_OUTPUT"
            echo "collector-builder-tag=${DEFAULT_BUILDER_TAG}" >> "$GITHUB_OUTPUT"
          else
            #We have 2 options:
            #- We build the builder from scratch and give it a custom tag
            #- We use the existing cache
            COLLECTOR_BUILDER_TAG="${DEFAULT_BUILDER_TAG}"
            if [[ "${{ contains(github.event.pull_request.labels.*.name, 'build-builder-image') }}" == "true" ]]; then
              COLLECTOR_BUILDER_TAG="${{ inputs.collector-tag }}"
              echo 'build-builder-image=true' >> "$GITHUB_OUTPUT"
            fi

            echo "collector-builder-tag=$COLLECTOR_BUILDER_TAG" >> "$GITHUB_OUTPUT"
          fi

  create-multiarch-manifest:
    needs:
    - set-environment
    name: Create Multiarch manifest
    runs-on: ubuntu-latest
    env:
      BUILD_BUILDER_IMAGE: ${{ needs.set-environment.outputs.build-builder-image }}
      COLLECTOR_BUILDER_TAG: ${{ needs.set-environment.outputs.collector-builder-tag }}

    steps:

      - name: Login to quay.io/stackrox-io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_STACKROX_IO_RW_USERNAME }}
          password: ${{ secrets.QUAY_STACKROX_IO_RW_PASSWORD }}


      - name: Create and push multiarch manifest for stackrox-io -slim
        run: |
          docker manifest create quay.io/stackrox-io/collector:${{ inputs.collector-tag }}-slim \
                                 quay.io/stackrox-io/collector:${{ inputs.collector-tag }}-amd64-slim \
                                 quay.io/stackrox-io/collector:${{ inputs.collector-tag }}-ppc64le-slim

          docker manifest push quay.io/stackrox-io/collector:${{ inputs.collector-tag }}-slim

      - name: Create and push multiarch manifest for stackrox-io -base
        run: |
          docker manifest create quay.io/stackrox-io/collector:${{ inputs.collector-tag }}-base \
                                 quay.io/stackrox-io/collector:${{ inputs.collector-tag }}-amd64-base \
                                 quay.io/stackrox-io/collector:${{ inputs.collector-tag }}-ppc64le-base

          docker manifest push quay.io/stackrox-io/collector:${{ inputs.collector-tag }}-base

      - name: Create and push multiarch manifest for builder to stackrox-io
        if: github.event_name == 'push' || needs.set-environment.outputs.collector-builder-tag != env.DEFAULT_BUILDER_TAG
        run: |
          docker manifest create "quay.io/stackrox-io/collector-builder:${COLLECTOR_BUILDER_TAG}" \
                                 "quay.io/stackrox-io/collector-builder:${COLLECTOR_BUILDER_TAG}-amd64" \
                                 "quay.io/stackrox-io/collector-builder:${COLLECTOR_BUILDER_TAG}-ppc64le"

          docker manifest push "quay.io/stackrox-io/collector-builder:${COLLECTOR_BUILDER_TAG}"

      - name: Login to quay.io/rhacs-eng
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_RHACS_ENG_RW_USERNAME }}
          password: ${{ secrets.QUAY_RHACS_ENG_RW_PASSWORD }}


      - name: Create and push multiarch manifest for rhacs-eng -slim
        run: |
          docker manifest create quay.io/rhacs-eng/collector:${{ inputs.collector-tag }}-slim \
                                quay.io/rhacs-eng/collector:${{ inputs.collector-tag }}-amd64-slim \
                                quay.io/rhacs-eng/collector:${{ inputs.collector-tag }}-ppc64le-slim

          docker manifest push quay.io/rhacs-eng/collector:${{ inputs.collector-tag }}-slim

      - name: Create and push multiarch manifest for rhacs-eng -base
        run: |
          docker manifest create quay.io/rhacs-eng/collector:${{ inputs.collector-tag }}-base \
                                quay.io/rhacs-eng/collector:${{ inputs.collector-tag }}-amd64-base \
                                quay.io/rhacs-eng/collector:${{ inputs.collector-tag }}-ppc64le-base

          docker manifest push quay.io/rhacs-eng/collector:${{ inputs.collector-tag }}-base

      - name: Create and push multiarch manifest for builder to rhacs-eng
        if: github.event_name == 'push' || needs.set-environment.outputs.collector-builder-tag != env.DEFAULT_BUILDER_TAG
        run: |
          docker manifest create "quay.io/rhacs-eng/collector-builder:${COLLECTOR_BUILDER_TAG}" \
                                 "quay.io/rhacs-eng/collector-builder:${COLLECTOR_BUILDER_TAG}-amd64" \
                                 "quay.io/rhacs-eng/collector-builder:${COLLECTOR_BUILDER_TAG}-ppc64le"

          docker manifest push "quay.io/rhacs-eng/collector-builder:${COLLECTOR_BUILDER_TAG}"
