name: Nightly drivers tests

on:
  schedule:
    - cron: '0 6 * * *'
  pull_request: # remove finalising drivers branch
    types:
      - synchronize


jobs:
  integration-tests:
    uses: ./.github/workflows/integration-tests.yml
    with:
      collector-tag: 3.18.0
      collector-qa-tag: 1.1.2
    secrets: inherit
