name: Build and push support-packages

on:
  workflow_call:
    inputs:
      branch-name:
        type: string
        required: true
        description: Branch CI is running on
      upstream-drivers-bucket:
        type: string
        required: true
        description: Bucket holding the upstream drivers to package
      downstream-drivers-bucket:
        type: string
        required: true
        description: Bucket holding the downstream drivers to package
      support-packages-bucket:
        type: string
        required: true
        description: Bucket where support-packages will be pushed to
      public-support-packages-bucket:
        type: string
        required: true
        description: Public bucket where support-packages will be pushed to
      support-packages-index-bucket:
        type: string
        required: true
        description: Bucket to push the generated support-packages index file into


jobs:
  build-support-packages:
    runs-on: Beorn

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_COLLECTOR_SVC_ACCT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - uses: ./.github/actions/support-package-metadata
        with:
          branch-name: ${{ inputs.branch-name }}

      - name: Create driver-matrix.json
        uses: ./.github/actions/support-package-driver-matrix
        with:
          metadata-dir: /tmp/support-packages/metadata/module-versions
          upstream-drivers-bucket: gs://${{ inputs.upstream-drivers-bucket }}
          downstream-drivers-bucket: gs://${{ inputs.downstream-drivers-bucket }}

      - name: Create support-packages
        run: |
          ${{ github.workspace }}/kernel-modules/support-packages/04-create-support-packages.sh \
            ${{ github.workspace }}/collector/LICENSE-kernel-modules.txt \
            gs://${{ inputs.upstream-drivers-bucket }} \
            /tmp/support-packages/metadata \
            /tmp/support-packages/output \
            gs://${{ inputs.downstream-drivers-bucket }}

      - name: Create metadata.json
        uses: ./.github/actions/support-package-metadata-json
        with:
          support-pkg-dir: /tmp/support-packages/output

      - name: Push support-packages
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: /tmp/support-packages/output
          parent: false
          destination: ${{ inputs.support-packages-bucket }}/x86_64

      - name: Check disk usage
        shell: bash
        run: |
          df -k
          go env GOCACHE && du -hs "$(go env GOCACHE)"
          go env GOMODCACHE && du -hs "$(go env GOMODCACHE)"
          du -ks /*
          docker system df
